spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:C:/db/test
    username: test
    password: password
    driverClassName: org.h2.Driver
    continue-on-error: true
    platform: h2

  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            drop-script-source: drop-tables.sql